require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe SurvivorsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Survivor. As you add validations to Survivor, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    {name: "Jonh", age: 24, gender: :male, is_infected: false, complaints: 2}
  }

  let(:invalid_attributes) {
    {name: "", age: 0, gender: :male, is_infected: false, complaints: 2}
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SurvivorsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all survivors as @survivors" do
      survivor = Survivor.create! valid_attributes
      get :index, params: {}, session: valid_session
      expect(assigns(:survivors)).to eq([survivor])
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Survivor" do
        expect {
          post :create, params: {survivor: valid_attributes}, session: valid_session
        }.to change(Survivor, :count).by(1)
      end

      it "assigns a newly created survivor as @survivor" do
        post :create, params: {survivor: valid_attributes}, session: valid_session
        expect(assigns(:survivor)).to be_a(Survivor)
        expect(assigns(:survivor)).to be_persisted
      end
    end

  end


end
